apiVersion: v1
kind: Service
metadata:
  name: on-boarding-application
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  selector:
    app: on-boarding-application
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080